"""
domain — give every SOFI project a clean local domain (e.g. sakk.local).

Design (chosen with the user):
  - TLD .local, resolved via /etc/hosts (NOT dnsmasq — avoids the avahi/mDNS
    fight; `files` precedes `mdns` in nsswitch so the hosts entry wins).
  - One shared Caddy listening on :80, routing by Host header to each project's
    `php artisan serve` port. Caddy binds :80 rootless via cap_net_bind_service.
  - One-time `shamel domain init` does the privileged setup (sudo). After that,
    `register` / `up` / `down` / `rm` are zero-sudo for everyday use.

Flow:
  shamel domain init                 # once: install Caddy + setcap + sudoers + start
  shamel domain register <PRJ> [slug]# allocate port, write vhost, add hosts entry
  shamel domain up   <PRJ>           # start the project's php server on its port
  shamel domain down <PRJ>           # stop it
  shamel domain list                 # table: project · domain · port · state
  shamel domain rm   <PRJ>           # remove vhost + hosts entry
  shamel domain status               # is the shared proxy up?

new-project.sh calls `register` automatically (best-effort; skips if not init'd).
"""
from __future__ import annotations

import os
import re
import shutil
import signal
import subprocess
import sys
import urllib.request
from pathlib import Path

from . import paths

TLD = "local"
PORT_BASE = 8001          # first project port; subsequent projects get the next free
PORT_MAX = 8999
MARKER = "# shamel-domain"
# Pinned static Caddy build (linux amd64). Override with SOFI_CADDY_URL.
CADDY_URL = os.environ.get(
    "SOFI_CADDY_URL",
    "https://github.com/caddyserver/caddy/releases/download/v2.8.4/caddy_2.8.4_linux_amd64.tar.gz",
)


# ───────────────────────── paths / run state ─────────────────────────

def run_dir() -> Path:
    d = paths.repo_root() / ".claude" / ".shamel-run"
    return d


def caddy_dir() -> Path:
    return run_dir() / "caddy"


def sites_dir() -> Path:
    return caddy_dir() / "sites"


def php_dir() -> Path:
    return run_dir() / "php"


def caddyfile() -> Path:
    return caddy_dir() / "Caddyfile"


def local_bin() -> Path:
    return run_dir() / "bin"


def repo_hosts_helper() -> Path:
    return paths.tooling_dir() / "bin" / "shamel-hosts"


SYSTEM_HOSTS_HELPER = "/usr/local/sbin/shamel-hosts"
SUDOERS_FILE = "/etc/sudoers.d/shamel-domains"


def _ensure_dirs() -> None:
    for d in (run_dir(), caddy_dir(), sites_dir(), php_dir(), local_bin()):
        d.mkdir(parents=True, exist_ok=True)


def caddy_bin() -> str | None:
    """Resolve a usable caddy: PATH first, then our local install."""
    onpath = shutil.which("caddy")
    if onpath:
        return onpath
    local = local_bin() / "caddy"
    return str(local) if local.exists() else None


# ───────────────────────── helpers ─────────────────────────

def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")
    s = re.sub(r"-{2,}", "-", s)
    return s or "app"


_PORT_RE = re.compile(r"reverse_proxy\s+127\.0\.0\.1:(\d+)")


def _used_ports() -> dict[str, int]:
    """Map project → port from existing vhost snippets."""
    out: dict[str, int] = {}
    if not sites_dir().exists():
        return out
    for f in sites_dir().glob("*.caddy"):
        m = _PORT_RE.search(f.read_text(encoding="utf-8"))
        if m:
            out[f.stem] = int(m.group(1))
    return out


def _alloc_port(prj: str) -> int:
    used = _used_ports()
    if prj in used:
        return used[prj]                     # stable: keep the project's port
    taken = set(used.values())
    for p in range(PORT_BASE, PORT_MAX + 1):
        if p not in taken:
            return p
    raise RuntimeError(f"no free port in {PORT_BASE}-{PORT_MAX}")


def _vhost_path(prj: str) -> Path:
    return sites_dir() / f"{prj}.caddy"


def _domain_for(prj: str, slug: str | None) -> str:
    return f"{slug or slugify(prj)}.{TLD}"


def _read_domain(prj: str) -> tuple[str, int] | None:
    """Return (domain, port) for a registered project, else None."""
    f = _vhost_path(prj)
    if not f.exists():
        return None
    txt = f.read_text(encoding="utf-8")
    dm = re.search(r"http://([^\s{]+)", txt)
    pm = _PORT_RE.search(txt)
    if dm and pm:
        return dm.group(1), int(pm.group(1))
    return None


def _write_root_caddyfile() -> None:
    caddyfile().write_text(
        "# SOFI local-domain proxy — generated by `shamel domain`. Do not edit by hand.\n"
        "{\n"
        "\tauto_https off\n"
        "}\n"
        f"import {sites_dir()}/*.caddy\n",
        encoding="utf-8",
    )


def _caddy_running() -> bool:
    cb = caddy_bin()
    if not cb:
        return False
    # `caddy` daemon exposes an admin API; reload-against-running is the cheap probe.
    r = subprocess.run([cb, "version"], capture_output=True)
    if r.returncode != 0:
        return False
    # pgrep is the most portable liveness check for the started daemon.
    return subprocess.run(["pgrep", "-f", "caddy run"], capture_output=True).returncode == 0


def _reload_or_start_caddy() -> str:
    """Reload the running proxy, or start it if down. Returns a status word."""
    cb = caddy_bin()
    if not cb:
        raise RuntimeError("caddy not installed — run `shamel domain init` first")
    _write_root_caddyfile()
    if _caddy_running():
        subprocess.run([cb, "reload", "--config", str(caddyfile())], check=True)
        return "reloaded"
    subprocess.run([cb, "start", "--config", str(caddyfile())], check=True)
    return "started"


def _hosts_apply(op: str, name: str) -> bool:
    """Add/remove a hosts entry through the passwordless root helper.
    Returns True on success; False (with guidance) if init hasn't run."""
    if Path(SYSTEM_HOSTS_HELPER).exists():
        r = subprocess.run(["sudo", "-n", SYSTEM_HOSTS_HELPER, op, name])
        if r.returncode == 0:
            return True
    print(f"  ! could not edit /etc/hosts automatically. Run once:\n"
          f"      sudo {repo_hosts_helper()} {op} {name}\n"
          f"    (or `shamel domain init` to enable passwordless updates)",
          file=sys.stderr)
    return False


def _state_record(prj: str, domain: str, port: int) -> None:
    """Stamp domain+port into the project's STATE.md brain (idempotent)."""
    sf = paths.brain_file(prj, "STATE")
    if not sf.exists():
        return
    lines = sf.read_text(encoding="utf-8").splitlines()
    kv = {"local_domain": f"http://{domain}", "local_port": str(port)}
    seen = set()
    for i, ln in enumerate(lines):
        for k, v in kv.items():
            if ln.startswith(f"{k}:"):
                lines[i] = f"{k}: {v}"
                seen.add(k)
    add = [f"{k}: {v}" for k, v in kv.items() if k not in seen]
    if add:
        # insert after the title line if present, else append.
        idx = next((i for i, l in enumerate(lines) if l.startswith("title:")), len(lines) - 1)
        lines[idx + 1:idx + 1] = add
    sf.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ───────────────────────── php server (up/down) ─────────────────────────

def _backend_dir(prj: str) -> Path | None:
    """Find the Laravel/PHP app root: src/backend, backend, or project root."""
    base = paths.project_dir(prj)
    for cand in (base / "src" / "backend", base / "backend", base):
        if (cand / "artisan").exists() or (cand / "public" / "index.php").exists():
            return cand
    return None


def _pid_file(prj: str) -> Path:
    return php_dir() / f"{prj}.pid"


def _pid_alive(prj: str) -> int | None:
    pf = _pid_file(prj)
    if not pf.exists():
        return None
    try:
        pid = int(pf.read_text().strip())
        os.kill(pid, 0)
        return pid
    except (ValueError, ProcessLookupError, PermissionError):
        return None


# ───────────────────────── subcommands ─────────────────────────

def cmd_register(prj: str, slug: str | None) -> int:
    if not paths.project_exists(prj):
        print(f"✗ no such project: {prj}", file=sys.stderr)
        return 2
    _ensure_dirs()
    port = _alloc_port(prj)
    domain = _domain_for(prj, slug)
    _vhost_path(prj).write_text(
        f"# {prj} — generated by `shamel domain register`\n"
        f"http://{domain} {{\n"
        f"\treverse_proxy 127.0.0.1:{port}\n"
        f"}}\n",
        encoding="utf-8",
    )
    _hosts_apply("add", domain)
    proxy = "(proxy not running — `shamel domain init`)"
    if caddy_bin():
        try:
            proxy = _reload_or_start_caddy()
        except subprocess.CalledProcessError as e:
            proxy = f"(caddy error: {e})"
    _state_record(prj, domain, port)
    print(f"✓ {prj} → http://{domain}  (port {port}, proxy {proxy})")
    print(f"  start app:  shamel domain up {prj}")
    return 0


def cmd_up(prj: str) -> int:
    if not paths.project_exists(prj):
        print(f"✗ no such project: {prj}", file=sys.stderr)
        return 2
    reg = _read_domain(prj)
    if not reg:
        print(f"✗ {prj} has no domain yet — run: shamel domain register {prj}", file=sys.stderr)
        return 2
    domain, port = reg
    if _pid_alive(prj):
        print(f"• {prj} already up → http://{domain}")
        return 0
    app = _backend_dir(prj)
    if not app:
        print(f"✗ no PHP app found under projects/{prj} (need artisan or public/index.php)",
              file=sys.stderr)
        return 2
    _ensure_dirs()
    log = php_dir() / f"{prj}.log"
    if (app / "artisan").exists():
        cmd = ["php", "artisan", "serve", "--host=127.0.0.1", f"--port={port}"]
    else:
        cmd = ["php", "-S", f"127.0.0.1:{port}", "-t", "public"]
    with open(log, "ab") as lf:
        proc = subprocess.Popen(cmd, cwd=str(app), stdout=lf, stderr=lf,
                                start_new_session=True)
    _pid_file(prj).write_text(str(proc.pid))
    print(f"✓ {prj} up (pid {proc.pid}) → http://{domain}")
    print(f"  log: {log}")
    return 0


def cmd_down(prj: str) -> int:
    pid = _pid_alive(prj)
    if not pid:
        print(f"• {prj} not running")
        _pid_file(prj).unlink(missing_ok=True)
        return 0
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
    except ProcessLookupError:
        pass
    _pid_file(prj).unlink(missing_ok=True)
    print(f"✓ {prj} stopped (pid {pid})")
    return 0


def cmd_list() -> int:
    used = _used_ports()
    if not used:
        print("(no local domains registered — `shamel domain register <PRJ>`)")
        return 0
    print(f"{'PROJECT':22} {'DOMAIN':28} {'PORT':>5}  STATE")
    for prj in sorted(used):
        reg = _read_domain(prj)
        domain = reg[0] if reg else "?"
        port = reg[1] if reg else used[prj]
        state = "up" if _pid_alive(prj) else "down"
        print(f"{prj:22} {('http://' + domain):28} {port:>5}  {state}")
    return 0


def cmd_rm(prj: str) -> int:
    reg = _read_domain(prj)
    cmd_down(prj)
    vp = _vhost_path(prj)
    if vp.exists():
        vp.unlink()
    if reg:
        _hosts_apply("del", reg[0])
    if caddy_bin() and _caddy_running():
        try:
            _reload_or_start_caddy()
        except subprocess.CalledProcessError:
            pass
    print(f"✓ removed local domain for {prj}")
    return 0


def cmd_status() -> int:
    cb = caddy_bin()
    print("━━ shamel domain ━━")
    print(f"  caddy   : {cb or '✗ not installed (run: shamel domain init)'}")
    print(f"  proxy   : {'up on :80' if _caddy_running() else 'down'}")
    print(f"  hosts   : {'passwordless' if Path(SYSTEM_HOSTS_HELPER).exists() else 'manual sudo'}")
    print(f"  domains : {len(_used_ports())} registered")
    return 0


# ───────────────────────── init (privileged, one-time) ─────────────────────────

def _install_caddy() -> str:
    """Ensure a caddy binary exists; download the pinned static build if missing."""
    cb = caddy_bin()
    if cb:
        return cb
    _ensure_dirs()
    dest = local_bin() / "caddy"
    tgz = run_dir() / "caddy.tar.gz"
    print(f"  downloading Caddy → {dest}")
    try:
        urllib.request.urlretrieve(CADDY_URL, tgz)
        subprocess.run(["tar", "-xzf", str(tgz), "-C", str(local_bin()), "caddy"], check=True)
        tgz.unlink(missing_ok=True)
        dest.chmod(0o755)
    except Exception as e:
        raise RuntimeError(
            f"caddy download failed ({e}). Install caddy manually (apt/brew or "
            f"https://caddyserver.com/download) so it is on PATH, then re-run init."
        )
    return str(dest)


def cmd_init() -> int:
    """One-time privileged setup. Prompts for sudo. Idempotent."""
    print("━━ shamel domain init ━━")
    print("This sets up local-domain serving. It will use sudo for three things:")
    print("  1. setcap on the Caddy binary  (lets it bind :80 without running as root)")
    print("  2. install a root-owned hosts helper at", SYSTEM_HOSTS_HELPER)
    print("  3. a sudoers rule so future hosts updates need no password")
    print()
    _ensure_dirs()

    # 1. Caddy + bind capability. If Caddy already serves :80 (e.g. installed as a
    #    systemd service), it can already bind the port — skip setcap entirely.
    cb = _install_caddy()
    print(f"  caddy: {cb}")
    if _caddy_running():
        print("  bind  : Caddy already running on :80 (service mode) — setcap not needed")
    elif subprocess.run(["sudo", "setcap", "cap_net_bind_service=+ep", cb]).returncode != 0:
        print("  ✗ setcap failed — Caddy may need sudo to bind :80", file=sys.stderr)

    # 2. Root-owned copy of the hosts helper (NOT the user-writable repo copy —
    #    a passwordless-sudo target must be unmodifiable by the user).
    src = repo_hosts_helper()
    subprocess.run(["sudo", "install", "-o", "root", "-g", "root", "-m", "0755",
                    str(src), SYSTEM_HOSTS_HELPER], check=True)
    print(f"  hosts helper: {SYSTEM_HOSTS_HELPER} (root-owned)")

    # 3. sudoers rule scoped to exactly that root-owned helper, validated before install.
    user = os.environ.get("SUDO_USER") or os.environ.get("USER") or subprocess.run(
        ["id", "-un"], capture_output=True, text=True).stdout.strip()
    rule = f"{user} ALL=(root) NOPASSWD: {SYSTEM_HOSTS_HELPER}\n"
    tmp = run_dir() / "sudoers.shamel-domains"
    tmp.write_text(rule, encoding="utf-8")
    if subprocess.run(["sudo", "visudo", "-cf", str(tmp)]).returncode != 0:
        print("  ✗ sudoers rule failed validation — not installing", file=sys.stderr)
        return 1
    subprocess.run(["sudo", "install", "-o", "root", "-g", "root", "-m", "0440",
                    str(tmp), SUDOERS_FILE], check=True)
    tmp.unlink(missing_ok=True)
    print(f"  sudoers: {SUDOERS_FILE} (passwordless hosts updates for {user})")

    # 4. Start the shared proxy.
    status = _reload_or_start_caddy()
    print(f"  proxy: {status} on :80")
    print("\n✓ init done. Now: shamel domain register <PRJ>  →  shamel domain up <PRJ>")
    return 0


# ───────────────────────── dispatch ─────────────────────────

def run(action: str, prj: str | None, slug: str | None) -> int:
    if action == "init":
        return cmd_init()
    if action == "status":
        return cmd_status()
    if action == "list":
        return cmd_list()
    if action in ("register", "up", "down", "rm"):
        if not prj:
            print(f"✗ `shamel domain {action}` needs a project id", file=sys.stderr)
            return 2
        if action == "register":
            return cmd_register(prj, slug)
        if action == "up":
            return cmd_up(prj)
        if action == "down":
            return cmd_down(prj)
        if action == "rm":
            return cmd_rm(prj)
    print(f"✗ unknown domain action: {action} "
          f"(init|register|up|down|list|rm|status)", file=sys.stderr)
    return 2
