#!/usr/bin/env bash
# tool/bck/refactoring-surgeon/characterize-test.sh — Generate characterization test for legacy code
set -euo pipefail
SOFI_ROOT="${SOFI_ROOT:-$HOME/Desktop/Lorka}"
R="$(tput setaf 1)" G="$(tput setaf 2)" Y="$(tput setaf 3)" B="$(tput setaf 4)" X="$(tput sgr0)"

usage() { echo "Usage: $(basename $0) <PRJ-ID> <class-name> <method-name> [test-name]
Generate a PHPUnit characterization test that snapshots current behavior.
  class-name  Fully qualified, e.g., App\\Services\\PaymentService
  method-name Method to characterize
  test-name   Optional custom test method name
--help"; exit 0; }

PRJ="$1"; CLASS="${2:-}"; METHOD="${3:-}"; TNAME="${4:-}"
[ "$PRJ" = "--help" ] && usage
[ -z "$CLASS" ] && echo "${R}Error: class name required$X" && usage
[ -z "$METHOD" ] && echo "${R}Error: method name required$X" && usage

PRJ_DIR="$SOFI_ROOT/projects/$PRJ"
SHORT=$(echo "$CLASS" | awk -F'\\\\' '{print $NF}')
TNAME="${TNAME:-it_characterizes_${METHOD}}"
TEST_FILE="$PRJ_DIR/tests/Feature/${SHORT}CharacterizationTest.php"

[ ! -f "$TEST_FILE" ] && cat > "$TEST_FILE" <<PHP
<?php
namespace Tests\\Feature;
use Tests\\TestCase;
use $CLASS;

class ${SHORT}CharacterizationTest extends TestCase
{
    /**
     * Characterization test for $CLASS::$METHOD.
     * Generated by refactoring-surgeon.
     * Capture current behavior before refactoring.
     */
    public function ${TNAME}(): void
    {
        \$service = app(${SHORT}::class);

        // @todo: arrange — set up minimal valid input
        \$input = [];

        // Act
        \$result = \$service->${METHOD}(\$input);

        // Assert — snapshot current behavior
        // Replace with meaningful assertions after review
        \$this->assertNotNull(\$result);
        \$this->assertIsArray(\$result);
    }
}
PHP

echo "${G}Characterization test created:$X $TEST_FILE"
echo "${Y}Run:$X php artisan test --filter=${TNAME}"
